services:
  neo4j-benchmark:
    image: neo4j:2025.04.0-community
    container_name: neo4j-benchmark
    environment:
      - NEO4J_AUTH=neo4j/neo4j_test_password
      - NEO4J_initial_dbms_default__database=${NEO4J_DB}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_dbms_memory_transaction_total_max=1g
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data/databases:/data/databases
      - ./neo4j/data/transactions:/data/transactions
    deploy:
      resources:
        limits:
          memory: 5g